### ISSUE TITLE
Show me all the open orders

### ISSUE THREAD

**Issue by chrishobcroft** [lptfutures/lptOrderBook#2]
## Current situation

Currently, it is only possible to view the details of an order by inputting the `sellOrderCreator` address that created the order.

This hinders buyers from being able to select from all available open orders.

## Proposed solution

Feedback from early user testing was that it would be _essential_ to be able to show buyers a list of open orders, which could then be sorted by:

| Price * | Block | LPT | DAI | Collateral | % Collateral † |
|---------------|------------------|--------------|-----------------|--------------------|--------------------|
| 8.1159   | 7807680          | 34.5         | 280             | 28                 | 10%                |
| 8.0000   | 7807280          | 250          | 2000            | 300                | 15%                |
| 8.2000   | 7808000          | 2000         | 16400           | 4100               | 25%                |
| 8.0000             | 7791000          | 1            | 8               | 1                  | 12.5%              |

`*` Price = DAI ÷ LPT
 `†` % Collateral = Collateral ÷ DAI

**Comment by willjgriff** [comment]
This involves reintroducing the orderId which was in the first version. There are 2 approaches, one which requires sellers to check log statements for their orderId after submitting a sell order in order to know which order is there's. The other is to maintain a list of orders for a particular address in the contract allowing them to call a function to see their orderId's. Both increase complexity, the second approach increases complexity roughly twice as much as the first approach.

Both approaches will allow a buyer to retrieve all currently open orderIds. With Solidity in it's current state, they will not be able to return the order details at the same time, just orderIds. The buyer, without building a UI, will have to manually call another function with each orderId in order to see it's details.

Sorting orders by fields also has to be done in a UI, it's not practical to do directly on the blockchain, partly because you have to request details for each order as specified above.

**Comment by chrishobcroft** [comment]
Closing, as it is superseded by https://github.com/lptfutures/lptOrderBook/issues/4
