### ISSUE TITLE
I want to be able to set _deliveredByBlock to any block in the future

### ISSUE THREAD

**Issue by chrishobcroft** [lptfutures/lptOrderBook#3]
## Current behaviour

Currently, when calling `createLptSellOrder`, the contract will validate that the creator has at least the unbonding period in blocks between the current block, and the _deliveredByBlock. This is to safeguard against them

However it prohibits someone who has taken an LptSellOrder from creating their LptSellOrder part way through the unbonding period - i.e. hedging some / all of their exposure to the changing price of Livepeer Tokens.

**Starting:**
- **It's block 100**, the unbonding period is 7 rounds, each round is 10 blocks.
- The price of LPTUSD on the open market is $100

**Action:**
- Alice creates a LptSellOrder for 1 LPT, 100 DAI, 10 DAI collateral - to deliver by block 180
- Bob fills the order instantly, and Alice unbonds 1 LPT

**Time passes:**
- **It's block 140**, price of LPTUSD on the open market is $50
- Bob's 100 DAI deal for 1 LPT is looking expensive! He's lost $50 already...
- Bob is scared that the price will fall further, and wants to limit his losses

**Action:** 
- Bob creates a LptSellOrder for 1 LPT, 50 DAI, 5 DAI collateral - to deliver by block 190
- Charlie fills the order instantly.
- No unbonding required because Bob doesn't actually have any LPT to unbond.

**Time passes:**
- **It's block 179**, price of LPTUSD on the open market is $20
- Alice withdraws delivers 1 LPT to Bob, and receives 100 DAI (plus 10 she put in). She's happy.

**Time passes:**
- **It's block 189**, price of LPTUSD on the open market is $20
- Bob delivers 1 LPT to Charlie, and receives 50 DAI (plus 5 he put in). He's not as happy as Alice, _but he's happy to have been able to create the LptSellOrder to deliver within the unbonding period timeframe_

**Comment by willjgriff** [comment]
The title is misleading, you can already set the _deliveredByBlock to any block in the future.

To complete your explanation, the restriction is a safeguard to ensure a seller has enough time to unbond LPT in order to pay the buyer without them risking loosing their collateral. 

Removing this restriction means a seller who must unbond LPT before fulfilling an order must cancel their order at least the unbonding period length before the _deliveredByBlock they specified. Otherwise a buyer can commit to buy within this period and claim the sellers collateral before they have a chance to fulfil the order.

If this is a contract for securing the sale of bonded LPT, I do not recommend removing this restriction.

If this is not a contract for securing the sale of bonded LPT, then we need a better description of what it is for.

If you must have this functionality I would suggest adding a separate set of functions that create a separate set of orders which allow for the buying and selling of LPT unrestricted by bonding period lengths.

**Comment by chrishobcroft** [comment]
Thank you for the response.

Closing this further to simplification of the specification in the README.

**Comment by AaronAbuUsama** [comment]
Hey guys, this is a fantastic project ❤. I know this issue is closed but Just a few observations.

1. While there is an obvious utility to bound LPT token holders, making it easier for anyone to short LPT regardless if they already some bound massively increases the utility of the dapp

2. Given the fact that there is an asymmetric risk between the long and short side, a lot more focus needs to be on the long side of the UX. It needs to be as easy as possible to see what the best deal is and have all the information so they can calculate their fair price.
